# Build configuration for Windows
# Optimized to prevent PDB limit errors (LNK1318)

[build]
# Use default target directory
target-dir = "target"

# Windows-specific configuration to handle PDB limits
[target.x86_64-pc-windows-msvc]
# Optional: Use LLD linker for better PDB handling (uncomment if needed)
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]