# macOS uses the system linker by default which is already optimized
# No need to specify alternative linkers on macOS

# Enable incremental compilation for faster rebuilds
[profile.dev]
incremental = true

# Optimize debug builds slightly for faster compilation
[profile.dev.package."*"]
opt-level = 0
debug = true

# Fast release builds for development testing
[profile.dev-release]
inherits = "release"
opt-level = 2
debug = true
lto = false